### ISSUE TITLE
zmq version incompatible

### ISSUE THREAD

**Issue by HPrivakos** [str4d/bitcore-node-zcash#1]
Hello, the actual version of zmq (2.15.3) is not compatible with bitcore-node
I get the following error: 

```
/usr/lib/node_modules/bitcore-node-zcash/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module version mismatch. Expected 47, got 48.
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at bindings (/usr/lib/node_modules/bitcore-node-zcash/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/lib/node_modules/bitcore-node-zcash/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

I tried to change zmq version to 2.14.0 and it's work, so maybe change it in the package.json to force the 2.14.0 version?

**Comment by HPrivakos** [comment]
I tried on another system, and the version 2.15.3 of zmq works.
